services:
  vectordb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./Crawler/Crawler/dbElements:/app/Crawler/Crawler/dbElements
      - ./chroma_db:/app/chroma_db
    working_dir: /app/Crawler/Crawler/dbElements
    command: python run_pipeline.py
    environment:
      - PYTHONUNBUFFERED=1
      - ANONYMIZED_TELEMETRY=false
      - DO_NOT_TRACK=1